// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  download32: string;
  downloadButton: string;
  downloadIcon: string;
  downloadText: string;
  text1: string;
  text2: string;
  title: string;
  wrapper: string;
}
declare const cssExports: CssExports;
export default cssExports;
